mode: gui # shell
debug: True # False
# user_name: anon
daw:
  mrs_watson_32_exe_path: "plugins/tools/MrsWatson-0.9.8/Windows/mrswatson.exe"
  mrs_watson_64_exe_path: "plugins/tools/MrsWatson-0.9.8/Windows/mrswatson64.exe"
  nano_host_32_exe_path: "plugins/tools/Tone2 NanoHost v1.0.2/NanoHost32bit.exe"
  nano_host_64_exe_path: "plugins/tools/Tone2 NanoHost v1.0.2/NanoHost64bit.exe"
  memento:
    cache: 5
    file: 20
gui:
  width: 1280
  height: 720

hydra:
  run:
    dir: .
  output_subdir: null
